feat: add display options to navigation
googlemaps/react-native-navigation-sdk pull request #370
Opened 2024-12-03 08:47 UTC by illuminati1911

Adds display options to navigation:
```typescript
/**
 * Defines the options used by the Navigator for dislaying different elements.
 */
export interface DisplayOptions {
  /**
   * Configures whether destination markers are shown during navigation.
   * If true, destination markers are shown.
   */
  showDestinationMarkers?: boolean;
  /**
   * Configures whether stop signs are shown during navigation.
   * If true, stop signs are shown.
   */
  showStopSigns?: boolean;
  /**
   * Configures whether traffic lights are shown during navigation.
   * If true, traffic lights are shown.
   */
  showTrafficLights?: boolean;
}
```

- [ ] Tests pass
- [ ] Appropriate changes to documentation are included in the PR

2024-12-03 12:06 UTC, jokerttu requested changes
Small nits

2024-12-03 12:06 UTC, jokerttu commented on android/src/main/java/com/google/android/react/navsdk/NavModule.java
> +  public void setDestination(
setDestination could call setDestinations internally with array containing only the given waypoint

2024-12-03 12:06 UTC, jokerttu commented on android/src/main/java/com/google/android/react/navsdk/NavModule.java
> +      if (displayOptions != null) {
seems like displayOptions are only used when routingOptions are given.
so it is not possible to give only displayOptions?

2024-12-04 05:14 UTC, illuminati1911 commented on android/src/main/java/com/google/android/react/navsdk/NavModule.java
> +      if (displayOptions != null) {
> seems like displayOptions are only used when routingOptions are given. so it is not possible to give only displayOptions?

On Android there is no API call for that. So display options are only available if routing options are provided.

2024-12-04 05:32 UTC, illuminati1911 commented on android/src/main/java/com/google/android/react/navsdk/NavModule.java
> +  public void setDestination(
Done.

2024-12-04 07:56 UTC, jokerttu commented on android/src/main/java/com/google/android/react/navsdk/NavModule.java
> +      if (displayOptions != null) {
No, I think this is fine as this is limitation from the sdk below.
Anyway, I think developers always give routeoptions as those are quite important.

2024-12-04 07:58 UTC, jokerttu approved these changes
LGTM

2024-12-04 08:34 UTC, merged